import { bytesToBase64, base64ToBytes } from './imageBase64';
import type { BondType } from '$lib/types/bonds';
import type { ColorPalette } from '$lib/types/profile';

/**
 * Standard base64 (RFC 4648 §4) -> base64url (RFC 4648 §5): swap the two
 * non-alphanumeric characters for URL-safe ones and drop the padding. See
 * `buildShareUrl()`'s doc comment for why the share fragment uses this
 * instead of `encodeURIComponent(btoa(...))`.
 */
function toBase64Url(base64: string): string {
	return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/** Inverse of `toBase64Url()` — restores the standard alphabet and the
 * padding `atob()`/`base64ToBytes()` require (padding length is fully
 * determined by the unpadded length mod 4). */
function fromBase64Url(base64url: string): string {
	const base64 = base64url.replace(/-/g, '+').replace(/_/g, '/');
	return base64 + '='.repeat((4 - (base64.length % 4)) % 4);
}

/**
 * Gzip-compress a UTF-8 string via the native Compression Streams API — no
 * library needed (Chrome 80+, Firefox 113+, Safari 16.4+, all comfortably
 * within this app's baseline). Falls back to plain UTF-8 bytes, uncompressed,
 * when unavailable, rather than throwing; `gzipDecode()` sniffs the gzip
 * magic header rather than assuming, so a link generated by an old browser
 * still round-trips correctly on a modern one and vice versa.
 */
async function gzipEncode(text: string): Promise<Uint8Array<ArrayBuffer>> {
	if (typeof CompressionStream === 'undefined') {
		return Uint8Array.from(new TextEncoder().encode(text));
	}
	const stream = new Blob([text]).stream().pipeThrough(new CompressionStream('gzip'));
	return new Uint8Array(await new Response(stream).arrayBuffer());
}

/**
 * Inverse of `gzipEncode()`. Parameter pinned to `Uint8Array<ArrayBuffer>`
 * (not the wider default `Uint8Array<ArrayBufferLike>`, which also covers
 * `SharedArrayBuffer`) — `Blob`'s constructor requires the narrower type.
 */
async function gzipDecode(bytes: Uint8Array<ArrayBuffer>): Promise<string> {
	const isGzip = bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b;
	if (isGzip && typeof DecompressionStream !== 'undefined') {
		const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));
		const buffer = await new Response(stream).arrayBuffer();
		return new TextDecoder().decode(buffer);
	}
	return new TextDecoder().decode(bytes);
}

/**
 * Strip a *legacy* (pre-gzip) `#import...` URL wrapper down to the bare
 * encoded payload, normalized to standard base64 — or return the input
 * unchanged if it isn't wrapped in one (already a bare code, or raw JSON).
 * The current format (`#share-`, gzip-compressed) is handled directly in
 * `decodeSharePayloadString()`, since unlike these it needs an async
 * decompress step, not just a synchronous string transform.
 */
function extractLegacyShareCode(raw: string): string {
	if (raw.includes('#import-')) {
		return fromBase64Url(raw.split('#import-')[1]);
	}
	if (raw.includes('#import/')) {
		return decodeURIComponent(raw.split('#import/')[1]);
	}
	if (raw.includes('#import=')) {
		return decodeURIComponent(raw.split('#import=')[1]);
	}
	return raw;
}

/**
 * Decode a share-payload string into its underlying JSON text.
 *
 * Three call sites — `profile.svelte.ts`'s `parseSharePayload`,
 * `ScanImportModal.svelte`'s `handleImportData`, and `+page.svelte`'s
 * `#import`/`#share` hash effect — used to reimplement this independently
 * (see REFACTOR_PLAN.md, High H4). This is the single source of truth for
 * it now. Async because the current format needs an async gzip-decompress
 * step (see `buildShareUrl()`'s doc comment for the full history of why).
 *
 * Accepts, in order:
 *  1. A full share URL containing `#share-<base64url(gzip(json))>` (current).
 *  2. Legacy, uncompressed forms: `#import-<base64url-json>`,
 *     `#import/<uri-encoded-base64-json>`, and `#import=<uri-encoded-base64-json>`
 *     — kept so links, QR codes, and bookmarks generated before any of these
 *     fixes keep working.
 *  3. Raw JSON (starts with `{`).
 *  4. A bare base64 "sync code" (falls back to the raw string if it isn't
 *     valid base64, matching what every prior copy of this logic did).
 */
export async function decodeSharePayloadString(raw: string): Promise<string> {
	if (raw.includes('#share-')) {
		const compressed = base64ToBytes(fromBase64Url(raw.split('#share-')[1]));
		return gzipDecode(compressed);
	}

	const code = extractLegacyShareCode(raw);
	if (code.startsWith('{')) {
		return code;
	}
	try {
		return atob(code);
	} catch {
		return code;
	}
}

/**
 * Build a full share URL for an already-exported JSON payload — the inverse
 * of `decodeSharePayloadString()`'s URL branch, and the single place that
 * decides how the payload after `#` is encoded.
 *
 * Current format: `#share-<base64url(gzip(json))>`. History, because this
 * is the third attempt and the reasoning matters for the next one:
 *
 *  1. Original: `#import=<uri-encoded-base64-json>`. Several chat apps'
 *     link auto-detection (WhatsApp confirmed) linkifies `.../#import` and
 *     then stops, silently dropping everything after — on **iOS**
 *     specifically, not Windows/Android, where all of these formats have
 *     tested fine. iOS's system-wide link/data detection (used by
 *     Messages, WhatsApp-on-iOS, Mail, etc.) is measurably stricter than
 *     the JS-regex linkifiers desktop/Android clients use.
 *  2/3. Swapping the separator (`=` -> `/` -> `-`) and the payload encoding
 *     (`encodeURIComponent(btoa(...))` -> pure base64url) made zero
 *     difference on iOS even though every one of those variants worked
 *     fine on desktop — ruling out "the character set after `#`" as the
 *     actual cause. That pointed at **length**: iOS's data detector is
 *     understood to give up on recognizing very long fragments as a link
 *     at all, regardless of what characters they contain.
 *  4. This fix: gzip the JSON before encoding it, typically shrinking a
 *     repetitive JSON payload (`milestonePrefs`, `colorPalette`,
 *     `togetherSince`, etc. repeated per bond) well below half its original
 *     size, and switch the marker to `#share-` (shorter than `#import-`,
 *     and a clean, unambiguous way to tell "this needs gzip decompression"
 *     from every prior format, none of which do).
 *
 * If a future report shows even *this* getting truncated, the next lever
 * is reducing the *number of fields* actually shipped in the compact
 * payload (`exportJSON()`), not further encoding tricks — there's nothing
 * left to compress harder once gzip is already in the pipeline.
 */
export async function buildShareUrl(origin: string, json: string): Promise<string> {
	const compressed = await gzipEncode(json);
	return `${origin}/#share-${toBase64Url(bytesToBase64(compressed))}`;
}

export interface FullBackupInfo {
	bondCount: number;
}

/**
 * Detects a full multi-bond backup (`{ version: 2, bonds: [...] }`, the shape
 * produced by "Download JSON Backup (All Bonds)") in already-decoded JSON text,
 * distinctly from a single-bond partner invite.
 *
 * This distinction matters: `profileStore.importJSON()`'s branch for this shape
 * always replaces the *entire* local app state, regardless of the `mode`
 * argument passed to it — unlike the single-bond-invite branches, which respect
 * `'replace' | 'add'`. A full backup can't be meaningfully previewed as "one
 * incoming bond" (`parseSharePayload`'s `Partial<Bond>` return shape) either —
 * there's no single name/date to show. Callers must use this to route full
 * backups to an explicit, unambiguous "this replaces everything" confirmation
 * instead of the single-bond invite's Add-as-New/Replace-Current flow, whose
 * buttons would otherwise silently wipe every bond already on the device. See
 * REFACTOR_PLAN.md, Phase 7 / M4.
 */
export function detectFullBackup(jsonString: string): FullBackupInfo | null {
	try {
		const data = JSON.parse(jsonString);
		if (data?.version === 2 && Array.isArray(data.bonds) && data.bonds.length > 0) {
			return { bondCount: data.bonds.length };
		}
	} catch {
		// Not JSON — not a backup either. Let the caller's existing parse path
		// produce the appropriate "invalid format" error.
	}
	return null;
}

export type ImportPayloadKind = 'full-backup' | 'single-bond' | 'legacy';

export interface ImportPreviewBond {
	names: string;
	type: BondType;
	/** Mirrors `normalizeIncomingBond()`'s own `raw.colorPalette ||
	 * envelope.colorPalette || 'rose'` fallback exactly, so the preview's
	 * per-bond accent color matches what the bond will actually be
	 * imported with. */
	colorPalette: ColorPalette;
	/** `data:<mimeType>;base64,<...>` if the record has an inline backup
	 * photo (`{ photo: { dataBase64, mimeType } }`, produced by
	 * `exportBackupJSON()`), directly usable as an `<img src>` — else
	 * `null`. Never a `sharedImage` relay reference: JSON *file* backups
	 * (the only payloads this function ever sees) always use the inline
	 * `photo` shape, never the compact QR/link path's relay reference, so
	 * there's no network-fetch-during-preview concern here (Invariant 11). */
	photoDataUrl: string | null;
}

export interface ImportPreview {
	kind: ImportPayloadKind;
	bonds: ImportPreviewBond[];
}

type PreviewBondLike = {
	names?: string;
	type?: string;
	colorPalette?: string;
	photo?: { dataBase64?: string; mimeType?: string };
};

/** Shared by all three shapes below — a bond-like record's preview fields
 * (`import(...).bond`, one entry of `import(...).bonds`, or a flat V1
 * record) always live in the same place relative to that record.
 * `envelope` is the top-level parsed payload, for `colorPalette`'s
 * per-bond-then-app-wide fallback (V1 legacy passes itself as both). */
function toPreviewBond(b: PreviewBondLike, envelope: PreviewBondLike = b): ImportPreviewBond {
	const validPalettes: ColorPalette[] = ['rose', 'lavender', 'terracotta', 'sage', 'midnight'];
	const rawPalette = b?.colorPalette || envelope?.colorPalette;
	return {
		names: b?.names || 'Unnamed bond',
		type: b?.type === 'friendship' ? 'friendship' : 'romantic',
		colorPalette: validPalettes.includes(rawPalette as ColorPalette) ? (rawPalette as ColorPalette) : 'rose',
		photoDataUrl:
			b?.photo?.dataBase64 && b?.photo?.mimeType
				? `data:${b.photo.mimeType};base64,${b.photo.dataBase64}`
				: null
	};
}

/**
 * Classify a raw JSON import payload (a selected backup *file*, not a
 * share code/link) into the shape it will be treated as, plus enough info
 * (bond names, type, photo) to render a preview before actually importing
 * anything.
 *
 * The three conditions below are a deliberate, exact mirror of
 * `profileStore.importJSON()`'s Case 1/2/3 detection (`profile.svelte.ts`)
 * — kept as a second, separately-maintained copy rather than a shared
 * helper because `importJSON()` needs the full parsed `data` to build real
 * Bond records via `normalizeIncomingBond()`, not just a names list, so
 * unifying them would mean refactoring already-tested, data-loss-sensitive
 * import logic for little benefit. If you ever change what shape counts as
 * a full backup / single-bond invite / legacy profile here, update
 * `importJSON()`'s matching condition too (and vice versa) — otherwise the
 * preview drawer (`JsonImportPreviewDrawer.svelte`) can end up showing
 * something different from what actually gets imported on confirm.
 */
export function classifyImportPayload(jsonString: string): ImportPreview | null {
	try {
		const data = JSON.parse(jsonString);

		if (data?.version === 2 && Array.isArray(data.bonds) && data.bonds.length > 0) {
			return { kind: 'full-backup', bonds: data.bonds.map((b: PreviewBondLike) => toPreviewBond(b, data)) };
		}
		if (data?.isSingleBond && data?.bond?.names && data?.bond?.togetherSince) {
			return { kind: 'single-bond', bonds: [toPreviewBond(data.bond, data)] };
		}
		if (data?.togetherSince && data?.names) {
			return { kind: 'legacy', bonds: [toPreviewBond(data)] };
		}
	} catch {
		// Not valid JSON — nothing to preview. Let the caller's existing
		// "invalid file format" error handling take over.
	}
	return null;
}
