import { bytesToBase64, base64ToBytes } from './imageBase64';

/**
 * Standard base64 (RFC 4648 §4) -> base64url (RFC 4648 §5): swap the two
 * non-alphanumeric characters for URL-safe ones and drop the padding. See
 * `buildShareUrl()`'s doc comment for why the share fragment uses this
 * instead of `encodeURIComponent(btoa(...))`.
 */
function toBase64Url(base64: string): string {
	return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/** Inverse of `toBase64Url()` — restores the standard alphabet and the
 * padding `atob()`/`base64ToBytes()` require (padding length is fully
 * determined by the unpadded length mod 4). */
function fromBase64Url(base64url: string): string {
	const base64 = base64url.replace(/-/g, '+').replace(/_/g, '/');
	return base64 + '='.repeat((4 - (base64.length % 4)) % 4);
}

/**
 * Gzip-compress a UTF-8 string via the native Compression Streams API — no
 * library needed (Chrome 80+, Firefox 113+, Safari 16.4+, all comfortably
 * within this app's baseline). Falls back to plain UTF-8 bytes, uncompressed,
 * when unavailable, rather than throwing; `gzipDecode()` sniffs the gzip
 * magic header rather than assuming, so a link generated by an old browser
 * still round-trips correctly on a modern one and vice versa.
 */
async function gzipEncode(text: string): Promise<Uint8Array<ArrayBuffer>> {
	if (typeof CompressionStream === 'undefined') {
		return Uint8Array.from(new TextEncoder().encode(text));
	}
	const stream = new Blob([text]).stream().pipeThrough(new CompressionStream('gzip'));
	return new Uint8Array(await new Response(stream).arrayBuffer());
}

/**
 * Inverse of `gzipEncode()`. Parameter pinned to `Uint8Array<ArrayBuffer>`
 * (not the wider default `Uint8Array<ArrayBufferLike>`, which also covers
 * `SharedArrayBuffer`) — `Blob`'s constructor requires the narrower type.
 */
async function gzipDecode(bytes: Uint8Array<ArrayBuffer>): Promise<string> {
	const isGzip = bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b;
	if (isGzip && typeof DecompressionStream !== 'undefined') {
		const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));
		const buffer = await new Response(stream).arrayBuffer();
		return new TextDecoder().decode(buffer);
	}
	return new TextDecoder().decode(bytes);
}

/**
 * Strip a *legacy* (pre-gzip) `#import...` URL wrapper down to the bare
 * encoded payload, normalized to standard base64 — or return the input
 * unchanged if it isn't wrapped in one (already a bare code, or raw JSON).
 * The current format (`#share-`, gzip-compressed) is handled directly in
 * `decodeSharePayloadString()`, since unlike these it needs an async
 * decompress step, not just a synchronous string transform.
 */
function extractLegacyShareCode(raw: string): string {
	if (raw.includes('#import-')) {
		return fromBase64Url(raw.split('#import-')[1]);
	}
	if (raw.includes('#import/')) {
		return decodeURIComponent(raw.split('#import/')[1]);
	}
	if (raw.includes('#import=')) {
		return decodeURIComponent(raw.split('#import=')[1]);
	}
	return raw;
}

/**
 * Decode a share-payload string into its underlying JSON text.
 *
 * Three call sites — `profile.svelte.ts`'s `parseSharePayload`,
 * `ScanImportModal.svelte`'s `handleImportData`, and `+page.svelte`'s
 * `#import`/`#share` hash effect — used to reimplement this independently
 * (see REFACTOR_PLAN.md, High H4). This is the single source of truth for
 * it now. Async because the current format needs an async gzip-decompress
 * step (see `buildShareUrl()`'s doc comment for the full history of why).
 *
 * Accepts, in order:
 *  1. A full share URL containing `#share-<base64url(gzip(json))>` (current).
 *  2. Legacy, uncompressed forms: `#import-<base64url-json>`,
 *     `#import/<uri-encoded-base64-json>`, and `#import=<uri-encoded-base64-json>`
 *     — kept so links, QR codes, and bookmarks generated before any of these
 *     fixes keep working.
 *  3. Raw JSON (starts with `{`).
 *  4. A bare base64 "sync code" (falls back to the raw string if it isn't
 *     valid base64, matching what every prior copy of this logic did).
 */
export async function decodeSharePayloadString(raw: string): Promise<string> {
	if (raw.includes('#share-')) {
		const compressed = base64ToBytes(fromBase64Url(raw.split('#share-')[1]));
		return gzipDecode(compressed);
	}

	const code = extractLegacyShareCode(raw);
	if (code.startsWith('{')) {
		return code;
	}
	try {
		return atob(code);
	} catch {
		return code;
	}
}

/**
 * Build a full share URL for an already-exported JSON payload — the inverse
 * of `decodeSharePayloadString()`'s URL branch, and the single place that
 * decides how the payload after `#` is encoded.
 *
 * Current format: `#share-<base64url(gzip(json))>`. History, because this
 * is the third attempt and the reasoning matters for the next one:
 *
 *  1. Original: `#import=<uri-encoded-base64-json>`. Several chat apps'
 *     link auto-detection (WhatsApp confirmed) linkifies `.../#import` and
 *     then stops, silently dropping everything after — on **iOS**
 *     specifically, not Windows/Android, where all of these formats have
 *     tested fine. iOS's system-wide link/data detection (used by
 *     Messages, WhatsApp-on-iOS, Mail, etc.) is measurably stricter than
 *     the JS-regex linkifiers desktop/Android clients use.
 *  2/3. Swapping the separator (`=` -> `/` -> `-`) and the payload encoding
 *     (`encodeURIComponent(btoa(...))` -> pure base64url) made zero
 *     difference on iOS even though every one of those variants worked
 *     fine on desktop — ruling out "the character set after `#`" as the
 *     actual cause. That pointed at **length**: iOS's data detector is
 *     understood to give up on recognizing very long fragments as a link
 *     at all, regardless of what characters they contain.
 *  4. This fix: gzip the JSON before encoding it, typically shrinking a
 *     repetitive JSON payload (`milestonePrefs`, `colorPalette`,
 *     `togetherSince`, etc. repeated per bond) well below half its original
 *     size, and switch the marker to `#share-` (shorter than `#import-`,
 *     and a clean, unambiguous way to tell "this needs gzip decompression"
 *     from every prior format, none of which do).
 *
 * If a future report shows even *this* getting truncated, the next lever
 * is reducing the *number of fields* actually shipped in the compact
 * payload (`exportJSON()`), not further encoding tricks — there's nothing
 * left to compress harder once gzip is already in the pipeline.
 */
export async function buildShareUrl(origin: string, json: string): Promise<string> {
	const compressed = await gzipEncode(json);
	return `${origin}/#share-${toBase64Url(bytesToBase64(compressed))}`;
}

export interface FullBackupInfo {
	bondCount: number;
}

/**
 * Detects a full multi-bond backup (`{ version: 2, bonds: [...] }`, the shape
 * produced by "Download JSON Backup (All Bonds)") in already-decoded JSON text,
 * distinctly from a single-bond partner invite.
 *
 * This distinction matters: `profileStore.importJSON()`'s branch for this shape
 * always replaces the *entire* local app state, regardless of the `mode`
 * argument passed to it — unlike the single-bond-invite branches, which respect
 * `'replace' | 'add'`. A full backup can't be meaningfully previewed as "one
 * incoming bond" (`parseSharePayload`'s `Partial<Bond>` return shape) either —
 * there's no single name/date to show. Callers must use this to route full
 * backups to an explicit, unambiguous "this replaces everything" confirmation
 * instead of the single-bond invite's Add-as-New/Replace-Current flow, whose
 * buttons would otherwise silently wipe every bond already on the device. See
 * REFACTOR_PLAN.md, Phase 7 / M4.
 */
export function detectFullBackup(jsonString: string): FullBackupInfo | null {
	try {
		const data = JSON.parse(jsonString);
		if (data?.version === 2 && Array.isArray(data.bonds) && data.bonds.length > 0) {
			return { bondCount: data.bonds.length };
		}
	} catch {
		// Not JSON — not a backup either. Let the caller's existing parse path
		// produce the appropriate "invalid format" error.
	}
	return null;
}
